spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3306}/payment?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:19092

kafka:
  enabled: true